name: happy_shop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_number_input: ^0.7.0+2
  splash_screen_view: ^3.0.0
  bottom_navy_bar: ^6.0.0
  flutter_svg: ^0.22.0
  line_awesome_flutter: ^2.0.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  modal_bottom_sheet: ^2.0.0
  another_xlider: ^1.0.0
  material_floating_search_bar: ^0.3.6
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.5
  sms_autofill: ^2.2.0
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  csc_picker: ^0.2.6
  top_snackbar_flutter: ^1.0.1
  dash_chat: ^1.1.16
  shared_preferences: ^2.0.8
  geolocator: ^7.7.1
  geocoding: ^2.0.1 
  empty_widget: ^0.0.5
  geoflutterfire: ^3.0.1
  photo_view: ^0.13.0
  step_progress_indicator: ^1.0.1
  flutter_typeahead: ^3.2.1
  direct_select_flutter: ^1.1.1
  argon_buttons_flutter: ^1.1.0
  dropdown_search: ^2.0.0
  favorite_button: ^0.0.4
  uuid: ^3.0.5
  readmore: ^2.1.0
  fluttertoast: ^8.0.8
  outline_search_bar: ^2.2.0
  bottom_picker: ^1.0.4
  bottom_dialog: ^1.0.3
  firestore_search: ^0.1.6
  ha_firestore_scaffold: ^0.0.2
 
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
flutter_app_name:
  name: "Happy Shop"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"


  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/fonts/
   - assets/images/logo/
   - assets/images/
   - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Name
      fonts:
        - asset: assets/fonts/name.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/SFUIText-Bold.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/SFUIText-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/SFUIText-Semibold.ttf
    - family: Sarina
      fonts:
        - asset: assets/fonts/Sarina-Regular.ttf
      
      
      
 